### PR TITLE
security improvement

### PR DESCRIPTION
**Pull request by VasylRudnitskyi**

### CODE REVIEW

**Comment by markwahl-msft** [comment]
Acknowledgement to finder of issue <a href="https://www.kilala.nl">T. Sluijter</a>.

**Comment by tsluyter** [comment]
> Acknowledgement to finder of issue [T. Sluijter](https://www.kilala.nl).

Thanks for the acknowledgement, I appreciate it! 

I've gone over the modifications to roles.js and I don't really see changes that would fix the XSS I'd found. But maybe that's because Javascript isn't my forté. I'll give it another look.

**Comment by VasylRudnitskyi** [comment]
>           > Acknowledgement to finder of issue [T. Sluijter](https://www.kilala.nl).
> 
> 
> Thanks for the acknowledgement, I appreciate it!
> I've gone over the modifications to roles.js and I don't really see changes that would fix the XSS I'd found. But maybe that's because Javascript isn't my forté. I'll give it another look.

We have changed rendering of user input value from 'as html' to 'as text', this made by next changes:
"columnDefs":  [
			{ targets: [0, 5, 6], render: $.fn.dataTable.render.text() }, 
		],
Where targets is numbers of column which represent values provided by user as 'Display Name', 'Description' or 'Justification'

**Comment by tsluyter** [comment]
EDIT: removed the comment. Let’s discuss the rest privately.

**Comment by VasylRudnitskyi** [comment]
>           EDIT: removed the comment. Let’s discuss the rest privately.

This fix make save users who use this specific sample, 
for described in your removed comment issue  I've opened bug, as it out of scope of PAM Portal sample. 
For communication or in case of any questions please mail me v-varudn@microsoft.com

**Comment by tsluyter** [comment]
I will email you. I have already submitted the bug/vulnerability in question

**Comment by ntonyho** [comment]
If you consider the systems being independent, each system should sufficiently protect itself without making assuming on the data from external systems

The web app should not trust the data from external systems including but not limited to SQL, active directory.

Otherwise, I will just put JavaScript as my display name in my active directory user / group object

**Pull request merged**
